name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          IMAGE_URI=${{ secrets.ECR_REPOSITORY }}:latest
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

  terraform-deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    env:
      TF_API_TOKEN: ${{ secrets.TFC_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.3

      - name: Terraform Init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TFC_API_TOKEN }}
        working-directory: ./terraform-deploy
        run: terraform init

      - name: Terraform Plan
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TFC_API_TOKEN }}
        working-directory: ./terraform-deploy
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TFC_API_TOKEN }}
        working-directory: ./terraform-deploy
        run: terraform apply -auto-approve tfplan